/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime.js';
import type {
  PostConvertPayloadToTransaction200Response,
  PostConvertPayloadToTransactionRequest,
  PostConvertPublicKeyToPlainAddress200Response,
  PostConvertPublicKeyToPlainAddressRequest,
  PostConvertUnresolvedAddressToPlainAddress200Response,
  PostConvertUnresolvedAddressToPlainAddressRequest
} from '../models/index.js';
export interface ConvertApiPostConvertPayloadToTransactionOperationRequest {
  postConvertPayloadToTransactionRequest: PostConvertPayloadToTransactionRequest;
}
export interface ConvertApiPostConvertPublicKeyToPlainAddressOperationRequest {
  postConvertPublicKeyToPlainAddressRequest: PostConvertPublicKeyToPlainAddressRequest;
}
export interface ConvertApiPostConvertUnresolvedAddressToPlainAddressOperationRequest {
  postConvertUnresolvedAddressToPlainAddressRequest: PostConvertUnresolvedAddressToPlainAddressRequest;
}
/**
 * ConvertApi - interface
 *
 * @export
 * @interface ConvertApiInterface
 */
export interface ConvertApiInterface {
  /**
   *
   * @summary transaction payload to json transaction object
   * @param {PostConvertPayloadToTransactionRequest} postConvertPayloadToTransactionRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConvertApiInterface
   */
  postConvertPayloadToTransactionRaw(
    requestParameters: ConvertApiPostConvertPayloadToTransactionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PostConvertPayloadToTransaction200Response>>;
  /**
   * transaction payload to json transaction object
   */
  postConvertPayloadToTransaction(
    requestParameters: ConvertApiPostConvertPayloadToTransactionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PostConvertPayloadToTransaction200Response>;
  /**
   *
   * @summary public-key to plain address
   * @param {PostConvertPublicKeyToPlainAddressRequest} postConvertPublicKeyToPlainAddressRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConvertApiInterface
   */
  postConvertPublicKeyToPlainAddressRaw(
    requestParameters: ConvertApiPostConvertPublicKeyToPlainAddressOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PostConvertPublicKeyToPlainAddress200Response>>;
  /**
   * public-key to plain address
   */
  postConvertPublicKeyToPlainAddress(
    requestParameters: ConvertApiPostConvertPublicKeyToPlainAddressOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PostConvertPublicKeyToPlainAddress200Response>;
  /**
   *
   * @summary unresolved address to plain address
   * @param {PostConvertUnresolvedAddressToPlainAddressRequest} postConvertUnresolvedAddressToPlainAddressRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ConvertApiInterface
   */
  postConvertUnresolvedAddressToPlainAddressRaw(
    requestParameters: ConvertApiPostConvertUnresolvedAddressToPlainAddressOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PostConvertUnresolvedAddressToPlainAddress200Response>>;
  /**
   * unresolved address to plain address
   */
  postConvertUnresolvedAddressToPlainAddress(
    requestParameters: ConvertApiPostConvertUnresolvedAddressToPlainAddressOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PostConvertUnresolvedAddressToPlainAddress200Response>;
}
/**
 *
 */
export declare class ConvertApi extends runtime.BaseAPI implements ConvertApiInterface {
  /**
   * transaction payload to json transaction object
   */
  postConvertPayloadToTransactionRaw(
    requestParameters: ConvertApiPostConvertPayloadToTransactionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PostConvertPayloadToTransaction200Response>>;
  /**
   * transaction payload to json transaction object
   */
  postConvertPayloadToTransaction(
    requestParameters: ConvertApiPostConvertPayloadToTransactionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PostConvertPayloadToTransaction200Response>;
  /**
   * public-key to plain address
   */
  postConvertPublicKeyToPlainAddressRaw(
    requestParameters: ConvertApiPostConvertPublicKeyToPlainAddressOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PostConvertPublicKeyToPlainAddress200Response>>;
  /**
   * public-key to plain address
   */
  postConvertPublicKeyToPlainAddress(
    requestParameters: ConvertApiPostConvertPublicKeyToPlainAddressOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PostConvertPublicKeyToPlainAddress200Response>;
  /**
   * unresolved address to plain address
   */
  postConvertUnresolvedAddressToPlainAddressRaw(
    requestParameters: ConvertApiPostConvertUnresolvedAddressToPlainAddressOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PostConvertUnresolvedAddressToPlainAddress200Response>>;
  /**
   * unresolved address to plain address
   */
  postConvertUnresolvedAddressToPlainAddress(
    requestParameters: ConvertApiPostConvertUnresolvedAddressToPlainAddressOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PostConvertUnresolvedAddressToPlainAddress200Response>;
}
