/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime.js';
import type { GetNodes200Response, NetworkType } from '../models/index.js';
export interface NodeApiGetNodesRequest {
  networkType?: NetworkType;
}
/**
 * NodeApi - interface
 *
 * @export
 * @interface NodeApiInterface
 */
export interface NodeApiInterface {
  /**
   *
   * @summary get living node
   * @param {NetworkType} [networkType] default value is mainnet
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof NodeApiInterface
   */
  getNodesRaw(
    requestParameters: NodeApiGetNodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetNodes200Response>>;
  /**
   * get living node
   */
  getNodes(
    requestParameters: NodeApiGetNodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetNodes200Response>;
}
/**
 *
 */
export declare class NodeApi extends runtime.BaseAPI implements NodeApiInterface {
  /**
   * get living node
   */
  getNodesRaw(
    requestParameters: NodeApiGetNodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetNodes200Response>>;
  /**
   * get living node
   */
  getNodes(
    requestParameters?: NodeApiGetNodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetNodes200Response>;
}
