/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime.js';
export interface QrcodeApiGetQrCodeForAddressRequest {
  address: string;
  name?: string;
}
/**
 * QrcodeApi - interface
 *
 * @export
 * @interface QrcodeApiInterface
 */
export interface QrcodeApiInterface {
  /**
   *
   * @summary Get QR Code for Address
   * @param {string} address
   * @param {string} [name]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof QrcodeApiInterface
   */
  getQrCodeForAddressRaw(
    requestParameters: QrcodeApiGetQrCodeForAddressRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Blob>>;
  /**
   * Get QR Code for Address
   */
  getQrCodeForAddress(
    requestParameters: QrcodeApiGetQrCodeForAddressRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Blob>;
}
/**
 *
 */
export declare class QrcodeApi extends runtime.BaseAPI implements QrcodeApiInterface {
  /**
   * Get QR Code for Address
   */
  getQrCodeForAddressRaw(
    requestParameters: QrcodeApiGetQrCodeForAddressRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Blob>>;
  /**
   * Get QR Code for Address
   */
  getQrCodeForAddress(
    requestParameters: QrcodeApiGetQrCodeForAddressRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Blob>;
}
