/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime.js';
import type { GetApiStatus200Response } from '../models/index.js';
/**
 * RootApi - interface
 *
 * @export
 * @interface RootApiInterface
 */
export interface RootApiInterface {
  /**
   *
   * @summary get api status
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RootApiInterface
   */
  getApiStatusRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetApiStatus200Response>>;
  /**
   * get api status
   */
  getApiStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetApiStatus200Response>;
}
/**
 *
 */
export declare class RootApi extends runtime.BaseAPI implements RootApiInterface {
  /**
   * get api status
   */
  getApiStatusRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetApiStatus200Response>>;
  /**
   * get api status
   */
  getApiStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetApiStatus200Response>;
}
