/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AccountActivityBucketsInner } from './AccountActivityBucketsInner.js';
import type { AccountSupplementalPublicKeys } from './AccountSupplementalPublicKeys.js';
import type { Mosaic } from './Mosaic.js';
/**
 * mosaic 数量等を変換したアカウントオブジェクト
 * @export
 * @interface Account
 */
export interface Account {
  /**
   *
   * @type {number}
   * @memberof Account
   */
  version: number;
  /**
   *
   * @type {string}
   * @memberof Account
   */
  address: string;
  /**
   *
   * @type {number}
   * @memberof Account
   */
  addressHeight: number;
  /**
   *
   * @type {string}
   * @memberof Account
   */
  publicKey: string;
  /**
   *
   * @type {number}
   * @memberof Account
   */
  publicKeyHeight: number;
  /**
   *
   * @type {number}
   * @memberof Account
   */
  accountType: number;
  /**
   *
   * @type {AccountSupplementalPublicKeys}
   * @memberof Account
   */
  supplementalPublicKeys: AccountSupplementalPublicKeys;
  /**
   *
   * @type {Array<AccountActivityBucketsInner>}
   * @memberof Account
   */
  activityBuckets: Array<AccountActivityBucketsInner>;
  /**
   *
   * @type {Array<Mosaic>}
   * @memberof Account
   */
  mosaics: Array<Mosaic>;
  /**
   *
   * @type {number}
   * @memberof Account
   */
  importance: number;
  /**
   *
   * @type {number}
   * @memberof Account
   */
  importanceHeight: number;
}
/**
 * Check if a given object implements the Account interface.
 */
export declare function instanceOfAccount(value: object): boolean;
export declare function AccountFromJSON(json: any): Account;
export declare function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account;
export declare function AccountToJSON(value?: Account | null): any;
