/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AccountSupplementalPublicKeysVotingPublicKeysInner } from './AccountSupplementalPublicKeysVotingPublicKeysInner.js';
/**
 *
 * @export
 * @interface AccountSupplementalPublicKeysVoting
 */
export interface AccountSupplementalPublicKeysVoting {
  /**
   *
   * @type {Array<AccountSupplementalPublicKeysVotingPublicKeysInner>}
   * @memberof AccountSupplementalPublicKeysVoting
   */
  publicKeys: Array<AccountSupplementalPublicKeysVotingPublicKeysInner>;
}
/**
 * Check if a given object implements the AccountSupplementalPublicKeysVoting interface.
 */
export declare function instanceOfAccountSupplementalPublicKeysVoting(value: object): boolean;
export declare function AccountSupplementalPublicKeysVotingFromJSON(json: any): AccountSupplementalPublicKeysVoting;
export declare function AccountSupplementalPublicKeysVotingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AccountSupplementalPublicKeysVoting;
export declare function AccountSupplementalPublicKeysVotingToJSON(
  value?: AccountSupplementalPublicKeysVoting | null
): any;
