/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AccountSupplementalPublicKeysLinked
 */
export interface AccountSupplementalPublicKeysLinked {
  /**
   *
   * @type {string}
   * @memberof AccountSupplementalPublicKeysLinked
   */
  publicKey: string;
}
/**
 * Check if a given object implements the AccountSupplementalPublicKeysLinked interface.
 */
export declare function instanceOfAccountSupplementalPublicKeysLinked(value: object): boolean;
export declare function AccountSupplementalPublicKeysLinkedFromJSON(json: any): AccountSupplementalPublicKeysLinked;
export declare function AccountSupplementalPublicKeysLinkedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AccountSupplementalPublicKeysLinked;
export declare function AccountSupplementalPublicKeysLinkedToJSON(
  value?: AccountSupplementalPublicKeysLinked | null
): any;
