/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AccountSupplementalPublicKeysLinked } from './AccountSupplementalPublicKeysLinked.js';
import type { AccountSupplementalPublicKeysVoting } from './AccountSupplementalPublicKeysVoting.js';
/**
 *
 * @export
 * @interface AccountSupplementalPublicKeys
 */
export interface AccountSupplementalPublicKeys {
  /**
   *
   * @type {AccountSupplementalPublicKeysLinked}
   * @memberof AccountSupplementalPublicKeys
   */
  linked?: AccountSupplementalPublicKeysLinked;
  /**
   *
   * @type {AccountSupplementalPublicKeysLinked}
   * @memberof AccountSupplementalPublicKeys
   */
  node?: AccountSupplementalPublicKeysLinked;
  /**
   *
   * @type {AccountSupplementalPublicKeysLinked}
   * @memberof AccountSupplementalPublicKeys
   */
  vrf?: AccountSupplementalPublicKeysLinked;
  /**
   *
   * @type {AccountSupplementalPublicKeysVoting}
   * @memberof AccountSupplementalPublicKeys
   */
  voting?: AccountSupplementalPublicKeysVoting;
}
/**
 * Check if a given object implements the AccountSupplementalPublicKeys interface.
 */
export declare function instanceOfAccountSupplementalPublicKeys(value: object): boolean;
export declare function AccountSupplementalPublicKeysFromJSON(json: any): AccountSupplementalPublicKeys;
export declare function AccountSupplementalPublicKeysFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AccountSupplementalPublicKeys;
export declare function AccountSupplementalPublicKeysToJSON(value?: AccountSupplementalPublicKeys | null): any;
