/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * when create a acount object
 * @export
 * @interface CreatedAccount
 */
export interface CreatedAccount {
  /**
   *
   * @type {string}
   * @memberof CreatedAccount
   */
  address: string;
  /**
   *
   * @type {string}
   * @memberof CreatedAccount
   */
  publicKey: string;
  /**
   *
   * @type {string}
   * @memberof CreatedAccount
   */
  privateKey: string;
}
/**
 * Check if a given object implements the CreatedAccount interface.
 */
export declare function instanceOfCreatedAccount(value: object): boolean;
export declare function CreatedAccountFromJSON(json: any): CreatedAccount;
export declare function CreatedAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedAccount;
export declare function CreatedAccountToJSON(value?: CreatedAccount | null): any;
