/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { NetworkType } from './NetworkType.js';
/**
 *
 * @export
 * @interface GetApiStatus200Response
 */
export interface GetApiStatus200Response {
  /**
   *
   * @type {string}
   * @memberof GetApiStatus200Response
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof GetApiStatus200Response
   */
  name: string;
  /**
   *
   * @type {NetworkType}
   * @memberof GetApiStatus200Response
   */
  networkType: NetworkType;
}
/**
 * Check if a given object implements the GetApiStatus200Response interface.
 */
export declare function instanceOfGetApiStatus200Response(value: object): boolean;
export declare function GetApiStatus200ResponseFromJSON(json: any): GetApiStatus200Response;
export declare function GetApiStatus200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetApiStatus200Response;
export declare function GetApiStatus200ResponseToJSON(value?: GetApiStatus200Response | null): any;
