/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Mosaic
 */
export interface Mosaic {
  /**
   *
   * @type {string}
   * @memberof Mosaic
   */
  id: string;
  /**
   *
   * @type {number}
   * @memberof Mosaic
   */
  amount: number;
  /**
   *
   * @type {number}
   * @memberof Mosaic
   */
  divisibility?: number;
}
/**
 * Check if a given object implements the Mosaic interface.
 */
export declare function instanceOfMosaic(value: object): boolean;
export declare function MosaicFromJSON(json: any): Mosaic;
export declare function MosaicFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mosaic;
export declare function MosaicToJSON(value?: Mosaic | null): any;
