/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export declare const NetworkType: {
  readonly Testnet: 'testnet';
  readonly Mainnet: 'mainnet';
};
export type NetworkType = (typeof NetworkType)[keyof typeof NetworkType];
export declare function NetworkTypeFromJSON(json: any): NetworkType;
export declare function NetworkTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkType;
export declare function NetworkTypeToJSON(value?: NetworkType | null): any;
