/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { NetworkType } from './NetworkType.js';
/**
 * transaction payload
 * @export
 * @interface Node
 */
export interface Node {
  /**
   *
   * @type {string}
   * @memberof Node
   */
  domain: string;
  /**
   *
   * @type {number}
   * @memberof Node
   */
  port: number;
  /**
   *
   * @type {boolean}
   * @memberof Node
   */
  isSsl: boolean;
  /**
   *
   * @type {NetworkType}
   * @memberof Node
   */
  networkType: NetworkType;
}
/**
 * Check if a given object implements the Node interface.
 */
export declare function instanceOfNode(value: object): boolean;
export declare function NodeFromJSON(json: any): Node;
export declare function NodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Node;
export declare function NodeToJSON(value?: Node | null): any;
