/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * transaction payload
 * @export
 * @interface Payload
 */
export interface Payload {
  /**
   *
   * @type {string}
   * @memberof Payload
   */
  payload: string;
}
/**
 * Check if a given object implements the Payload interface.
 */
export declare function instanceOfPayload(value: object): boolean;
export declare function PayloadFromJSON(json: any): Payload;
export declare function PayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): Payload;
export declare function PayloadToJSON(value?: Payload | null): any;
