/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Payload } from './Payload.js';
/**
 *
 * @export
 * @interface PostConvertPayloadToTransactionRequest
 */
export interface PostConvertPayloadToTransactionRequest {
  /**
   *
   * @type {Payload}
   * @memberof PostConvertPayloadToTransactionRequest
   */
  from: Payload;
}
/**
 * Check if a given object implements the PostConvertPayloadToTransactionRequest interface.
 */
export declare function instanceOfPostConvertPayloadToTransactionRequest(value: object): boolean;
export declare function PostConvertPayloadToTransactionRequestFromJSON(
  json: any
): PostConvertPayloadToTransactionRequest;
export declare function PostConvertPayloadToTransactionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostConvertPayloadToTransactionRequest;
export declare function PostConvertPayloadToTransactionRequestToJSON(
  value?: PostConvertPayloadToTransactionRequest | null
): any;
