/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Address } from './Address.js';
/**
 *
 * @export
 * @interface PostConvertUnresolvedAddressToPlainAddress200Response
 */
export interface PostConvertUnresolvedAddressToPlainAddress200Response {
  /**
   *
   * @type {Address}
   * @memberof PostConvertUnresolvedAddressToPlainAddress200Response
   */
  result: Address;
}
/**
 * Check if a given object implements the PostConvertUnresolvedAddressToPlainAddress200Response interface.
 */
export declare function instanceOfPostConvertUnresolvedAddressToPlainAddress200Response(value: object): boolean;
export declare function PostConvertUnresolvedAddressToPlainAddress200ResponseFromJSON(
  json: any
): PostConvertUnresolvedAddressToPlainAddress200Response;
export declare function PostConvertUnresolvedAddressToPlainAddress200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostConvertUnresolvedAddressToPlainAddress200Response;
export declare function PostConvertUnresolvedAddressToPlainAddress200ResponseToJSON(
  value?: PostConvertUnresolvedAddressToPlainAddress200Response | null
): any;
