/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Transaction } from './Transaction.js';
/**
 *
 * @export
 * @interface PostConvertPayloadToTransaction200Response
 */
export interface PostConvertPayloadToTransaction200Response {
  /**
   *
   * @type {Transaction}
   * @memberof PostConvertPayloadToTransaction200Response
   */
  result: Transaction;
}
/**
 * Check if a given object implements the PostConvertPayloadToTransaction200Response interface.
 */
export declare function instanceOfPostConvertPayloadToTransaction200Response(value: object): boolean;
export declare function PostConvertPayloadToTransaction200ResponseFromJSON(
  json: any
): PostConvertPayloadToTransaction200Response;
export declare function PostConvertPayloadToTransaction200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostConvertPayloadToTransaction200Response;
export declare function PostConvertPayloadToTransaction200ResponseToJSON(
  value?: PostConvertPayloadToTransaction200Response | null
): any;
