/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { PublicKey } from './PublicKey.js';
/**
 *
 * @export
 * @interface PostConvertPublicKeyToPlainAddressRequest
 */
export interface PostConvertPublicKeyToPlainAddressRequest {
  /**
   *
   * @type {PublicKey}
   * @memberof PostConvertPublicKeyToPlainAddressRequest
   */
  from: PublicKey;
}
/**
 * Check if a given object implements the PostConvertPublicKeyToPlainAddressRequest interface.
 */
export declare function instanceOfPostConvertPublicKeyToPlainAddressRequest(value: object): boolean;
export declare function PostConvertPublicKeyToPlainAddressRequestFromJSON(
  json: any
): PostConvertPublicKeyToPlainAddressRequest;
export declare function PostConvertPublicKeyToPlainAddressRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostConvertPublicKeyToPlainAddressRequest;
export declare function PostConvertPublicKeyToPlainAddressRequestToJSON(
  value?: PostConvertPublicKeyToPlainAddressRequest | null
): any;
