/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Transaction
 */
export interface Transaction {
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  signature: string;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  signerPublicKey: string;
  /**
   *
   * @type {number}
   * @memberof Transaction
   */
  version: number;
  /**
   *
   * @type {number}
   * @memberof Transaction
   */
  network: number;
  /**
   *
   * @type {number}
   * @memberof Transaction
   */
  type: number;
  /**
   *
   * @type {number}
   * @memberof Transaction
   */
  maxFee: number;
  /**
   *
   * @type {number}
   * @memberof Transaction
   */
  deadline: number;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  message?: string;
  /**
   *
   * @type {Array<object>}
   * @memberof Transaction
   */
  mosaics?: Array<object>;
}
/**
 * Check if a given object implements the Transaction interface.
 */
export declare function instanceOfTransaction(value: object): boolean;
export declare function TransactionFromJSON(json: any): Transaction;
export declare function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction;
export declare function TransactionToJSON(value?: Transaction | null): any;
