/**
 * Symbol REST Wrapper
 * API server that makes development more convenient
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UnresolvedAddress
 */
export interface UnresolvedAddress {
  /**
   *
   * @type {string}
   * @memberof UnresolvedAddress
   */
  unresolvedAddress: string;
}
/**
 * Check if a given object implements the UnresolvedAddress interface.
 */
export declare function instanceOfUnresolvedAddress(value: object): boolean;
export declare function UnresolvedAddressFromJSON(json: any): UnresolvedAddress;
export declare function UnresolvedAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnresolvedAddress;
export declare function UnresolvedAddressToJSON(value?: UnresolvedAddress | null): any;
